INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '1', 'Город', 0, 'Город');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '2', 'Село', 1, 'Село');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '3', 'Деревня', 2, 'Деревня');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '4', 'Район', 3, 'Район');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '5', 'Поселок', 4, 'Поселок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '6', 'Поселок городского типа', 5, 'Поселок городского типа');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '7', 'Военный городок', 6, 'Военный городок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '8', 'Воинская часть', 7, 'Воинская часть');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '9', 'Санаторий', 8, 'Санаторий');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '10', 'Больница', 9, 'Больница');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '11', 'Совхоз', 10, 'Совхоз');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '12', 'Колхоз', 11, 'Колхоз');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '13', 'Аал', 12, 'Аал');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '14', 'Аул', 13, 'Аул');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '15', 'Волость', 14, 'Волость');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '16', 'Выселки(ок)', 15, 'Выселки(ок)');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '17', 'Городок', 16, 'Городок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '18', 'Дачный поселок', 17, 'Дачный поселок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '19', 'Железнодорожная будка', 18, 'Железнодорожная будка');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '20', 'Железнодорожная казарма', 19, 'Железнодорожная казарма');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '21', 'ж/д останов. (обгонный) пункт', 20, 'ж/д останов. (обгонный) пункт');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '22', 'Железнодорожный пост', 21, 'Железнодорожный пост');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '23', 'Железнодорожный разъезд', 22, 'Железнодорожный разъезд');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '24', 'Железнодорожная платформа', 23, 'Железнодорожная платформа');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '25', 'Железнодорожная станция', 24, 'Железнодорожная станция');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '26', 'Заимка', 25, 'Заимка');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '27', 'Казарма', 26, 'Казарма');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '28', 'Курортный поселок', 27, 'Курортный поселок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '29', 'Местечко', 28, 'Местечко');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '30', 'Микрорайон', 29, 'Микрорайон');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '31', 'Остров', 30, 'Остров');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '32', 'Почтовое отделение', 31, 'Почтовое отделение');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '33', 'Планировочный район', 32, 'Планировочный район');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '34', 'Поселок и(при) станция(и)', 33, 'Поселок и(при) станция(и)');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '35', 'Починок', 34, 'Починок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '36', 'Промышленная зона', 35, 'Промышленная зона');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '37', 'Разъезд', 36, 'Разъезд');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '38', 'Рабочий поселок', 37, 'Рабочий поселок');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '39', 'Садовое неком-е товарищество', 38, 'Садовое неком-е товарищество');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '40', 'Слобода', 39, 'Слобода');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '41', 'Станция', 40, 'Станция');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '42', 'Станица', 41, 'Станица');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '43', 'Территория', 42, 'Территория');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '44', 'Улус', 43, 'Улус');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '45', 'Хутор', 44, 'Хутор');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '46', 'Квартал', 45, 'Квартал');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '47', 'Арбан', 46, 'Арбан');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '48', 'Леспромхоз', 47, 'Леспромхоз');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '49', 'Погост', 48, 'Погост');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '50', 'Кордон', 49, 'Кордон');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '51', 'Населенный пункт', 50, 'Населенный пункт');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '52', 'Сельская администрация', 51, 'Сельская администрация');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '53', 'Сумон', 52, 'Сумон');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '54', 'Сельский округ', 53, 'Сельский округ');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '55', 'Сельское муницип. образование', 54, 'Сельское муницип. образование');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '56', 'Сельское поселение', 55, 'Сельское поселение');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '57', 'Сельсовет', 56, 'Сельсовет');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '58', 'Массив', 57, 'Массив');
INSERT INTO CatalogData (`catalog_id`, `label`, `value`, `sort`, `value_api`) VALUES (44, '59', 'Сельское муниципальное образование', 58, 'Сельское муниципальное образование');
